print("Bienvenido a pizza planeta. Para poder tomar su pedido en línea, por favor, llene los siguientes datos")
nombre = input ("Nombre: ")
edad = input ("Edad: ")
telefono = input ("Teléfono: ")
direccion = input ("Dirección: ")
mail = input ("Correo electrónico: ")
nacionalidad = input ("Nacionalidad: ")
print ("Para proceder con el pedido de su pizza confirme que sus datos son correctos")
print (f"Usted es {nombre} de {edad} años \nSu teléfono es {telefono} \nLa pizza se entregará en {direccion} \nSu correo es: {mail} \nSu nacionalidad es {nacionalidad}")